# Generated by Django 4.2.27 on 2026-01-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                (
                    "ontology_path",
                    models.CharField(
                        default="ontology/default_ontology.json",
                        help_text="相对于MEDIA_ROOT的路径",
                        max_length=500,
                        verbose_name="本体论文件路径",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500, verbose_name="文件名")),
                (
                    "pdf_path",
                    models.CharField(
                        help_text="相对于MEDIA_ROOT的路径",
                        max_length=500,
                        verbose_name="PDF文件路径",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "mineru_output_path",
                    models.CharField(
                        blank=True,
                        help_text="Markdown文件路径",
                        max_length=500,
                        null=True,
                        verbose_name="MinerU输出路径",
                    ),
                ),
                (
                    "extraction_output_path",
                    models.CharField(
                        blank=True,
                        help_text="本体论JSON文件路径",
                        max_length=500,
                        null=True,
                        verbose_name="提取输出路径",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="text_extraction.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
                "db_table": "file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_by", "is_deleted"], name="project_created_855639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="project_created_86fac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["project", "status"], name="file_project_c66f50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["task_id"], name="file_task_id_68618c_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["created_at"], name="file_created_8fb939_idx"),
        ),
    ]
