# Generated by Django 4.2.27 on 2026-01-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extraction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="", max_length=255, verbose_name="项目描述"),
        ),
        migrations.AlterField(
            model_name="project",
            name="ontology_path",
            field=models.CharField(
                default="ontology_v2.json",
                help_text="相对于MEDIA_ROOT的路径",
                max_length=500,
                verbose_name="本体论文件路径",
            ),
        ),
    ]
