# Generated by Django 4.2.27 on 2026-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extraction", "0002_project_description_alter_project_ontology_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.IntegerField(default=0, verbose_name="文件大小kb"),
        ),
    ]
